default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: chochu
  pool: 5

development:
  <<: *default
  database: thami_backend_development

test:
  <<: *default
  database: thami_backend_test
